### PR TITLE
Apply black 24.1 formatting

### PR DESCRIPTION
**Pull request by Alexsandruss**
New rules in black 24.1 version failed CI Lint check.
This PR applies black 24.1.0 formatting to code base.

### CODE REVIEW

**Review by icfaust — APPROVED** [review]
Pull when CI is complete (assuming good CI)

**Comment by napetrov** [comment]
@Alexsandruss  @icfaust  - should we pin black versioning so it will be controlled within sources?  Can be done as separate change

**Comment by icfaust** [comment]
I think thats a good idea

**Pull request merged**
