### PR TITLE
TEST: disabled LogReg SPMD test case

### PR DESCRIPTION
**Pull request by samir-nasibli**
### Description

Disabling LogReg test cases for SPMD for big tol for float64.
There are CI jobs with fails:
* http://intel-ci.intel.com/ef6c415f-ce15-f17b-8e05-a4bf010d0e2e
* http://intel-ci.intel.com/ef6c48c0-6256-f199-8547-a4bf010d0e2e
* http://intel-ci.intel.com/ef6c5487-20a2-f133-8e51-a4bf010d0e2e
* http://intel-ci.intel.com/ef6cad4d-ad75-f10d-8e05-a4bf010d0e2e
   * it fails on different tol.
* http://intel-ci.intel.com//ef6d6379-a76d-f152-a00f-a4bf010d0e2e

where this failure is happen. Make sense just disable this case instead of reverting #2029

---

Checklist to comply with before moving PR from draft:

**PR completeness and readability**

- [ ] I have reviewed my changes thoroughly before submitting this pull request.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation to reflect the changes or created a separate PR with update and provided its number in the description, if necessary.
- [ ] Git commit message contains an appropriate signed-off-by string _(see [CONTRIBUTING.md](https://github.com/intel/scikit-learn-intelex/blob/main/CONTRIBUTING.md#pull-requests) for details)_.
- [ ] I have added a respective label(s) to PR if I have a permission for that.  
- [ ] I have resolved any merge conflicts that might occur with the base branch.

**Testing**

- [ ] The unit tests pass successfully.
- [ ] I have run it locally and tested the changes extensively.

**Performance**

- [ ] I have measured performance for affected algorithms using [scikit-learn_bench](https://github.com/IntelPython/scikit-learn_bench) and provided at least summary table with measured data, if performance change is expected.
- [ ] I have provided justification why performance has changed or why changes are not expected.

### CODE REVIEW

**Comment by samir-nasibli** [comment]
* http://intel-ci.intel.com/ef6cad4d-ad75-f10d-8e05-a4bf010d0e2e
   * it fails on different tol.
 updating the disabling condition

**Comment by avolkov-intel** [comment]
Managed to reproduce it on a separate branch, have no objections to merge this PR

**Review by avolkov-intel — APPROVED** [review]

**Review by ethanglaser — APPROVED** [review]

**Review by syakov-intel — APPROVED** [review]
approved to merge

**Pull request merged**
