### PR TITLE
MAINT: aligning gpu interfaces y param with sklearn

### PR DESCRIPTION
**Pull request by ethanglaser**
# Description
scikit-learn provides dummy y variable in cluster/compute ([example](https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/decomposition/_incremental_pca.py#L201)) interfaces for general alignment - we mostly have this implemented in our daal4py/sklearnex cpu interfaces already. It's not used in sklearn or in sklearnex but provides uniform interfaces and will be useful in resolving common sklbench errors.

also adds queue as kwarg when passing in cases where its not already done.

### CODE REVIEW

**Comment by samir-nasibli** [comment]
@ethanglaser could you please reference sklearn_bench where this fix is required?

**Comment by samir-nasibli** [comment]
> @ethanglaser could you please reference sklearn_bench where this fix is required?

Is it required for spmd ifaces?

**Review by samir-nasibli — APPROVED** [review]

**Comment by ethanglaser** [comment]
> > @ethanglaser could you please reference sklearn_bench where this fix is required?
> 
> Is it required for spmd ifaces?

It mostly depends on config files setup, but in cases where same datasets are used for multiple algos (ie higgs for kmeans, linreg) it will pass dummy y data and breaks spmd interfaces that dont have dummy data in this case. Since this would align with our d4p/cpu and stock sklearn interfaces, and avoids this issue, it probably would be good do here.

**Comment by ethanglaser** [comment]
Based on internal CI there is just an issue with empty result options on windows

**Comment by ethanglaser** [comment]
Any objections on this? Is it okay with API or is it considered breaking?

**Pull request merged**
