### PR TITLE
Add sklearn 1.4 version to CI matrix

### PR DESCRIPTION
**Pull request by Alexsandruss**
Sklearn has recently released 1.4 into conda/pip and the CI matrix should be updated.

Changes:
- Add python 3.12 + sklearn 1.4 job
- Fix Gram matrix warning message for sklearn 1.4 version in linear_model
- Fix kNN workflow for sklearn 1.4 version
- Fix csr_matrix/csr_array check in data_conversion
- Copy subset of deselected sklearn tests from gpu to main for 1.4 version

### CODE REVIEW

**Comment by icfaust** [comment]
#1640 has the fix for the lof test fail in it.

**Comment by samir-nasibli** [comment]
> #1640 has the fix for the lof test fail in it.

Is it possible to move that fix into separate branch and merge it asap?

**Comment by samir-nasibli** [comment]
> #1640 has the fix for the lof test fail in it.

@icfaust Is it possible to move that fix into separate branch and merge it asap?

**Comment by icfaust** [comment]
> > #1640 has the fix for the lof test fail in it.
> 
> @icfaust Is it possible to move that fix into separate branch and merge it asap?

Will do.

**Comment by icfaust** [comment]
PR #1657 has now been added to this PR, passes tests here and will now be closed.

**Comment by icfaust** [comment]
Looks like the last test failure is due to dual="auto" in this: https://github.com/scikit-learn/scikit-learn/blob/1.4.X/sklearn/svm/tests/test_svm.py#L669 
older versions of sklearn do not have this in the test

**Comment by icfaust** [comment]
It looks like [svm/tests/test_svm.py::test_auto_weight] is an RNG fail as the random_seed isn't set in the test for SVC or LogisticRegression, and the value has likely changed due to additional tests.

**Review by icfaust — APPROVED** [review]
LGTM

**Pull request merged**
