### PR TITLE
ENH: Python interfaces for Linear regression

### PR DESCRIPTION
**Pull request by KulikovNikita**
Refers to https://github.com/intel/scikit-learn-intelex/pull/1177

### CODE REVIEW

**Comment by KulikovNikita** [comment]
http://intel-ci.intel.com/edac7d98-e7a2-f1e2-8f30-a4bf010d0e2e

**Comment by KulikovNikita** [comment]
Previous CI on this exact HEAD: http://intel-ci.intel.com/edac66d9-b7db-f15e-b012-a4bf010d0e2e

**Comment by KulikovNikita** [comment]
http://intel-ci.intel.com/edac7e65-1e89-f104-b22b-a4bf010d0e2e

**Comment by KulikovNikita** [comment]
http://intel-ci.intel.com/edac80bf-c1e5-f195-8993-a4bf010d0e2e

**Review by Alexsandruss — APPROVED** [review]

**Pull request merged**
