### PR TITLE
FIX: daal4py sycl examples

### PR DESCRIPTION
**Pull request by samir-nasibli**
# Description
Please include a summary of the change. For large or complex changes please include enough information to introduce your change and explain motivation for it.

Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Review by Alexsandruss — COMMENTED** [review]
Rebase on master branch to fetch CI changes with dpc++ 2023.0 compiler and pytest for onedal/*

**Comment by napetrov** [comment]
@samir-nasibli  @Alexsandruss  - do we need this PR?

**Review by napetrov — APPROVED** [review]

**Pull request merged**
