### PR TITLE
Update GPU context in XPU tests

### PR DESCRIPTION
**Pull request by vlad-nazarov**

### CODE REVIEW

**Comment by vlad-nazarov** [comment]
http://intel-ci.intel.com/ec42c79a-bd39-f1a6-a848-8cdcd4b723a1

**Comment by napetrov** [comment]
are we going to merge this?

**Comment by vlad-nazarov** [comment]
Yes, but at first need to investigate timeouts in testing

**Review by napetrov — APPROVED** [review]

**Pull request merged**
