### PR TITLE
FIX: LinReg gpu tol issue

### PR DESCRIPTION
**Pull request by samir-nasibli**
# Description
LinReg gpu tol issue
fixes sporadically fail of:
```
linear_model/tests/test_linear_regression.py::test_full_results[float32-SyclQueue_GPU]
```

### CODE REVIEW

**Comment by samir-nasibli** [comment]
> I believe this line is the problem:
> 
> https://github.com/intel/scikit-learn-intelex/blob/d3ccbf4338932781a3fb48994edb794182b02bfa/onedal/linear_model/tests/test_linear_regression.py#L79

good catch 👍

**Review by ethanglaser — APPROVED** [review]
LGTM, let's wait for green CI

**Review by napetrov — APPROVED** [review]

**Pull request merged**
