### PR TITLE
Update `sed` command for sklearn version

### PR DESCRIPTION
**Pull request by Alexsandruss**
# Description
`sed` doesn't replace sklearn version correctly, this PR aims to fix it.

### CODE REVIEW

**Comment by Alexsandruss** [comment]
@Mergifyio rebase

**Comment by Alexsandruss** [comment]
Might be a sporadic failure, anyway, it's not scope of this PR:

MacOS Python3.10_Sklearn1.2
```
=================================== FAILURES ===================================
_______ test_forest_regressor_oob[X0-y0-0.7-array-RandomForestRegressor] _______
...
>       assert regressor.oob_score_ >= lower_bound_r2
E       assert 0.6929809093349724 >= 0.7
E        +  where 0.6929809093349724 = RandomForestRegressor(n_estimators=50, oob_score=True, random_state=0).oob_score_

ensemble/tests/test_forest.py:587: AssertionError
```

**Comment by samir-nasibli** [comment]
> Might be a sporadic failure, anyway, it's not scope of this PR:
> 
> MacOS Python3.10_Sklearn1.2
> 
> ```
> =================================== FAILURES ===================================
> _______ test_forest_regressor_oob[X0-y0-0.7-array-RandomForestRegressor] _______
> ...
> >       assert regressor.oob_score_ >= lower_bound_r2
> E       assert 0.6929809093349724 >= 0.7
> E        +  where 0.6929809093349724 = RandomForestRegressor(n_estimators=50, oob_score=True, random_state=0).oob_score_
> 
> ensemble/tests/test_forest.py:587: AssertionError
> ```

Please re-run job to check

**Review by ethanglaser — APPROVED** [review]

**Pull request merged**
