### PR TITLE
[testing] re-enable deselected PCA and LogisticRegression tests

### PR DESCRIPTION
**Pull request by icfaust**
# Description
PCA and GPU LogisticRegression are now out of preview, this PR checks to see what the status of CI. (There were no changes in moving PCA and LogisticRegression out of preview in #1570 and #1649, and frankly should have been done in those PRs).

Changes proposed in this pull request:
- modify deselected_tests.yaml

### CODE REVIEW

**Comment by icfaust** [comment]
CI is fully green.

**Review by md-shafiul-alam — APPROVED** [review]

**Pull request merged**
