### PR TITLE
Sigmoid Kernel

### PR DESCRIPTION
**Pull request by OnlyDeniko**
```python
from numpy import random as rng
from onedal.prims import sigmoid_kernel
X = np.array(5 * rng.random_sample((5, 4)))
Y = np.array(5 * rng.random_sample((8, 4)))
print(sigmoid_kernel(X, Y, gamma=0.01, coef0=1.0))
```

### CODE REVIEW

**Comment by OnlyDeniko** [comment]
/intelci: run
set branch=dev/sigmoid-kernel

**Review by PetrovKP — COMMENTED** [review]
Look good, add please simple tests for sigmoid, svm with sigmoid for dense and csr cases

**Comment by OnlyDeniko** [comment]
/intelci: run
set ext_build=ebd38dc6-2784-f1a2-92a7-8cdcd4b723a1

**Comment by OnlyDeniko** [comment]
/intelci: run
set ext_build=ebd38dc6-2784-f1a2-92a7-8cdcd4b723a1

**Comment by OnlyDeniko** [comment]
/intelci: run
set ext_build=ebd38dc6-2784-f1a2-92a7-8cdcd4b723a1

**Review by PetrovKP — APPROVED** [review]
After green CI (no problem from your changes)

**Pull request merged**
