### PR TITLE
Logistic Regression SPMD timeout temporary resolution

### PR DESCRIPTION
**Pull request by md-shafiul-alam**
Changes proposed in this pull request:
- Bump required version to 2024.4.0 to skip logistic regression spmd example during CI runs to avoid time out, will be reverted to 2024.1.0 once the issue is resolved

### CODE REVIEW

**Comment by ethanglaser** [comment]
Before merging it may be worth syncing with @avolkov-intel on this issue. For me I haven't encountered problems running spmd logreg via sklbench (contrary to previous kmeans issue)

**Review by samir-nasibli — COMMENTED** [review]
This issue is not related with backend version. So maybe we have another mechanism to skip this with a meaningful comment?

**Comment by md-shafiul-alam** [comment]
> This issue is not related with backend version. So maybe we have another mechanism to skip this with a meaningful comment?

It is true that the issue is not related to backend version, but this forces us to look back after the next release. A ticket has been created to actually investigate and resolve this. If there are no other issues except CI, we can even ignore it for now.

**Comment by ethanglaser** [comment]
If we don't want to complete "deselect" the example, we could see if small number of rows yields the same issue, and if not use that temporarily

**Comment by avolkov-intel** [comment]
This is a sporadic failure as it doesn't occur in 100% runs and now we are expecting difficulties with reproducing it. Therefore, I think it is better to keep this test enabled to see the timeout in nightly when it happens.

**Comment by md-shafiul-alam** [comment]
> This is a sporadic failure as it doesn't occur in 100% runs and now we are expecting difficulties with reproducing it. Therefore, I think it is better to keep this test enabled to see the timeout in nightly when it happens.

Agree, however, we have already observed the failures 4/5 times in last 7/8 nightlies. I think we should investigate this in the coming sprint.

**Review by ethanglaser — APPROVED** [review]

**Pull request merged**
