### PR TITLE
deps: add dependencies-dev to codeowners

### PR DESCRIPTION
**Pull request by ethanglaser**
# Description
Please include a summary of the change. For large or complex changes please include enough information to introduce your change and explain motivation for it.

Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Comment by ahuber21** [comment]
Would make sense to first merge #1648 and then rebase this PR

**Comment by ethanglaser** [comment]
> Would make sense to first merge #1648 and then rebase this PR

I guess it depends on if we want to remove Nikita as a codeowner, he is still reviewing PRs ;)

**Comment by napetrov** [comment]
i think those are not conflicting PRs? as they do change different lines?

**Review by napetrov — APPROVED** [review]

**Comment by ahuber21** [comment]
Yes, they are not conflicting, but the current CODEOWNERS is reported to be broken. I think Nikita no longer has write access or something...

**Pull request merged**
