### PR TITLE
Serialize support for new interfaces

### PR DESCRIPTION
**Pull request by PetrovKP**

### CODE REVIEW

**Comment by PetrovKP** [comment]
/intelci: run
set ext_build=ebb361d3-fdb0-f1bb-a928-8cdcd4b723a1

**Comment by PetrovKP** [comment]
/intelci: restart
set ext_build=ebb361d3-fdb0-f1bb-a928-8cdcd4b723a1

**Comment by owerbat** [comment]
There're some SVM tests in deselected list where serialization is checked. I think they should be checked and removed from there

**Comment by PetrovKP** [comment]
@owerbat , this should be fixed in this PR https://github.com/intel/scikit-learn-intelex/pull/625

**Comment by PetrovKP** [comment]
/intelci: run
set ext_build=ebb6eff5-a93c-f190-9b46-8cdcd4b723a1

**Review by owerbat — APPROVED** [review]

**Pull request merged**
