### PR TITLE
[testing] _onedal_cpu/gpu_supported design test

### PR DESCRIPTION
**Pull request by icfaust**
# Description
This will test if the design rule of having '_onedal_cpu_supported' and '_onedal_gpu_supported' methods in is followed for all patched estimators

Changes proposed in this pull request:
- Add test for _onedal_cpu_supported
- Add test for _onedal_gpu_supported

Tasks
- [x] Implement tests
- [x] Correct Failures

### CODE REVIEW

**Review by samir-nasibli — COMMENTED** [review]
Looks good to me. Just address some private CI failures.
@ethanglaser please check private CI failures status

**Review by ethanglaser — APPROVED** [review]
LGTM. All CI fails are related to catboost and should be resolved with rebase (or just re-running on feb 2 lol)

**Pull request merged**
