### PR TITLE
FIX: pca fit with dpctl/dpnp

### LINKED ISSUE #1534: PCA on gpu hangs
**Describe the bug**

I'm setting up a [benchmark project](https://github.com/soda-inria/sklearn-engine-benchmarks) to compare speed of similar algorithms with different backends (results are browsable in [this spreadsheet](https://docs.google.com/spreadsheets/d/1te_3jY6vI4wo3-V7xbmWQai5Mdh5plWdLst2ox0wuLM)), and I want to include `scikit-learn-intelex` performance whenever it's possible. Now working on a [PCA benchmark](https://github.com/soda-inria/sklearn-engine-benchmarks/pull/2), for scikit-learn-intelex PCA works fine on CPU but on GPU it just seems to hang. 

**To Reproduce**

```python
import numpy as np
import dpctl
import dpctl.tensor as dpt
from sklearnex.decomposition import PCA

rng = np.random.default_rng(123)
X = rng.random((2_000_000,100), dtype=np.float32)

device=dpctl.SyclDevice("gpu:level_zero")
X = dpt.asarray(X, copy=True, device=device)

pca = PCA(n_components=10, svd_solver="full")
# Also hangs
# pca = PCA(n_components=10)
pca.fit(X)
```

**Expected behavior**
Completes in a reasonable amount of time (seconds at most)

**Output/Screenshots**
No output, it just hangs.

**Environment:**

`scikit-learn-intelex==2023.2.1` installed with pip, in a conda environment, on intel beta dev cloud, running on max series gpu.

### PR DESCRIPTION
**Pull request by samir-nasibli**
# Description
fixes #1534

### CODE REVIEW

**Comment by samir-nasibli** [comment]
GPU CI validation: http://intel-ci.intel.com/ee6d0152-9671-f1ae-b4a0-a4bf010d0e2e.

**Comment by samir-nasibli** [comment]
> There are some fails in scikit-learn sklearnex tests as a result of this change (both public+private CI)

yeah, thank you! Currently investigating it

**Comment by md-shafiul-alam** [comment]
Lets wait for the CI run to be complete, so far green.

**Review by ethanglaser — APPROVED** [review]
Looks great

**Pull request merged**
