### PR TITLE
CI: remove SVM+neighbors GPU deselections

### PR DESCRIPTION
**Pull request by ethanglaser**
### Description

Unclear what changes made these no longer an issue, but looks like there are no device issues on svm and neighbors conformance tests. Adds 750+ GPU conformance tests back into validation.

---

Checklist to comply with before moving PR from draft:

**PR completeness and readability**

- [ ] I have reviewed my changes thoroughly before submitting this pull request.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation to reflect the changes or created a separate PR with update and provided its number in the description, if necessary.
- [ ] Git commit message contains an appropriate signed-off-by string _(see [CONTRIBUTING.md](https://github.com/intel/scikit-learn-intelex/blob/main/CONTRIBUTING.md#pull-requests) for details)_.
- [ ] I have added a respective label(s) to PR if I have a permission for that.  
- [ ] I have resolved any merge conflicts that might occur with the base branch.

**Testing**

- [ ] The unit tests pass successfully.
- [ ] I have run it locally and tested the changes extensively.

**Performance**

- [ ] I have measured performance for affected algorithms using [scikit-learn_bench](https://github.com/IntelPython/scikit-learn_bench) and provided at least summary table with measured data, if performance change is expected.
- [ ] I have provided justification why performance has changed or why changes are not expected.

### CODE REVIEW

**Review by icfaust — APPROVED** [review]
Crazy number of reactivations. Great job!

**Comment by icfaust** [comment]
Private CI failures unrelated to reactivated tests.

**Review by samir-nasibli — APPROVED** [review]
Amazing!

It would be good for the future to have a mechanism that would show how many tests were enabled within a certain fix.

As an idea, for this we can simply run tests without deselected and compare the crashes with the deselection list. It seems that it is not difficult to even automate

**Pull request merged**
