### PR TITLE
Refactoring package versions for build 

### PR DESCRIPTION
**Pull request by OnlyDeniko**

### CODE REVIEW

**Comment by OnlyDeniko** [comment]
/intelci: run
set infra_branch=dev/dkulandi/numpy_problem

**Comment by OnlyDeniko** [comment]
/intelci: run
set infra_branch=dev/dkulandi/numpy_problem

**Comment by OnlyDeniko** [comment]
/intelci: run
set infra_branch=dev/dkulandi/numpy_problem

**Comment by OnlyDeniko** [comment]
/intelci: run
set infra_branch=dev/dkulandi/numpy_problem

**Comment by OnlyDeniko** [comment]
/intelci: run
set infra_branch=dev/dkulandi/numpy_problem

**Comment by OnlyDeniko** [comment]
/intelci: run
set infra_branch=dev/dkulandi/numpy_problem

**Comment by OnlyDeniko** [comment]
/intelci: run
set infra_branch=dev/dkulandi/numpy_problem

**Comment by OnlyDeniko** [comment]
/intelci: run
set infra_branch=dev/dkulandi/numpy_problem

**Comment by OnlyDeniko** [comment]
/intelci: run
set infra_branch=dev/dkulandi/numpy_problem

**Review by PetrovKP — APPROVED** [review]

**Pull request merged**
