### PR TITLE
infra: disable MacOS public CI tests

### PR DESCRIPTION
**Pull request by ethanglaser**
# Description
Please include a summary of the change. For large or complex changes please include enough information to introduce your change and explain motivation for it.

Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Review by md-shafiul-alam — APPROVED** [review]
looks good to me

**Comment by ethanglaser** [comment]
I suppose this could be removed as its not currently being used: https://github.com/intel/scikit-learn-intelex/blob/main/.ci/pipeline/build-and-test-mac.yml. But if we are viewing this as a temporary disable then may not be necessary.

**Comment by napetrov** [comment]
> I suppose this could be removed as its not currently being used: https://github.com/intel/scikit-learn-intelex/blob/main/.ci/pipeline/build-and-test-mac.yml. But if we are viewing this as a temporary disable then may not be necessary. Any thoughts?

As i see this - if this is temporal - then will be recovered with revert, if it's permanent, then it's better to do complete removal

**Comment by ethanglaser** [comment]
> > I suppose this could be removed as its not currently being used: https://github.com/intel/scikit-learn-intelex/blob/main/.ci/pipeline/build-and-test-mac.yml. But if we are viewing this as a temporary disable then may not be necessary. Any thoughts?
> 
> As i see this - if this is temporal - then will be recovered with revert, if it's permanent, then it's better to do complete removal

Will leave it then, since goal would be to re-enable

**Pull request merged**
