### PR TITLE
DOC: Add info about incremental algorithms and BS (#2103)

### PR DESCRIPTION
**Pull request by olegkkruglov**
- Add 'Non-Scikit algorithms' part to the docs
- Add info about IncrementalPCA
- Add sphinx.napoleon extension to generate docs from docstrings.
- Update docstrings for non-scikit algorithms

## Description

_Add a comprehensive description of proposed changes_

_List associated issue number(s) if exist(s): #6 (for example)_

_Documentation PR (if needed): #1340 (for example)_

_Benchmarks PR (if needed): https://github.com/IntelPython/scikit-learn_bench/pull/155 (for example)_

---

Checklist to comply with **before moving PR from draft**:

**PR completeness and readability**

- [x] I have reviewed my changes thoroughly before submitting this pull request.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes or created a separate PR with update and provided its number in the description, if necessary.
- [x] Git commit message contains an appropriate signed-off-by string _(see [CONTRIBUTING.md](https://github.com/intel/scikit-learn-intelex/blob/main/CONTRIBUTING.md#pull-requests) for details)_.
- [x] I have added a respective label(s) to PR if I have a permission for that.
- [x] I have resolved any merge conflicts that might occur with the base branch.

**Testing**

- [x] I have run it locally and tested the changes extensively.
- [x] All CI jobs are green or I have provided justification why they aren't.
- [x] I have extended testing suite if new functionality was introduced in this PR.

**Performance**

- [x] I have measured performance for affected algorithms using [scikit-learn_bench](https://github.com/IntelPython/scikit-learn_bench) and provided at least summary table with measured data, if performance change is expected.
- [x] I have provided justification why performance has changed or why changes are not expected.
- [x] I have provided justification why quality metrics have changed or why changes are not expected.
- [x] I have extended benchmarking suite and provided corresponding scikit-learn_bench PR if new measurable functionality was introduced in this PR.

### CODE REVIEW

**Comment by samir-nasibli** [comment]
fails in this PR is not related with the changes.
Already resolved for the main branch with test deselections.
Could be ignored in the scope of this PR validation

**Review by samir-nasibli — APPROVED** [review]

**Comment by samir-nasibli** [comment]
@maria-Petrova here only docstrings are changed do we need to run internal CI?

**Comment by maria-Petrova** [comment]
@samir-nasibli, doc build in public CI is sufficient. Why condaEnv steps are failing?

**Comment by samir-nasibli** [comment]
Potentially this changes dependend on the PR https://github.com/intel/scikit-learn-intelex/pull/2038
I am not sure what is better partially bring those changes here, for BS attr renaming I mean or just update docstrings for the 2025.0 BS impl. From my prospective the second one more safe
@maria-Petrova @icfaust I would like to know your opinions as well

**Comment by samir-nasibli** [comment]
> @samir-nasibli, doc build in public CI is sufficient. Why condaEnv steps are failing?

I have already comment out, but now it comes to me that my prev comment https://github.com/intel/scikit-learn-intelex/pull/2112#issuecomment-2414503789 is not correct. I see fails, that already should be addressed on 2025.0 rls branch with the latest commits there.
@Vika-F @ethanglaser any thoughts?

**Comment by samir-nasibli** [comment]
@olegkkruglov what is the status?

**Review by samir-nasibli — APPROVED** [review]

**Pull request merged**
