### PR TITLE
[bug] adding _parameter_constraints to additional algos

### PR DESCRIPTION
**Pull request by ethanglaser**
# Description
Avoid stock sklearn conformance fail by adding _parameter_constraints to modules that don't have it

### CODE REVIEW

**Review by samir-nasibli — APPROVED** [review]
Looks good to me.
waiting CI

**Review by Alexsandruss — APPROVED** [review]
Assuming CI will be green.

**Comment by ethanglaser** [comment]
Based on CI, intended fix is working. There are sporadic issues that I see in other jobs as well - will create a ticket to address separately.

**Pull request merged**
