### PR TITLE
FIX: changing RF regressor default train method

### PR DESCRIPTION
**Pull request by samir-nasibli**
# Description
* removed not used import
* changing RF regressor default train method

[WIP]
# TODO
* disable test cases:
  * FAILED scikit-learn-intelex/onedal/ensemble/tests/test_random_forest.py::test_rf_regression[SyclQueue1] - AssertionError:                                                                                                                                                                                                            
  * FAILED scikit-learn-intelex/onedal/ensemble/tests/test_random_forest.py::test_rf_regression_random_splitter[SyclQueue] - AssertionError:

### CODE REVIEW

**Comment by ahuber21** [comment]
Why are you changing the default method?

**Review by KulikovNikita — APPROVED** [review]

**Comment by samir-nasibli** [comment]
> Why is this change required?

For RF classifier, ExtraTrees reg and classifier it is `hist`. 
1) consistency
2) dense is not supported on GPU

**Comment by samir-nasibli** [comment]
Job: http://intel-ci.intel.com/ee269223-c026-f195-b9bc-a4bf010d0e2e. Specifically for sklearnex/sklearn GPU.

**Comment by icfaust** [comment]
This was already patched and in discussion in https://github.com/intel/scikit-learn-intelex/pull/1333. Was there a reason to push this forward?

**Comment by samir-nasibli** [comment]
> This was already patched and in discussion in #1333. Was there a reason to push this forward?

I don't know what is the reason having such big PRs like #1333... It is better patch fixes in separate small commits.

**Comment by samir-nasibli** [comment]
> > This was already patched and in discussion in #1333. Was there a reason to push this forward?
> 
> I don't know what is the reason having such big PRs like #1333... 
It is better patch fixes in separate small commits. In this cases fixes will be in master much faster and review is more clear.

**Pull request merged**
