### PR TITLE
Replace DAALROOT with DALROOT

### PR DESCRIPTION
**Pull request by maria-Petrova**
The PR aims to replace DAALROOT with DALROOT for the upcoming releases.

### CODE REVIEW

**Comment by maria-Petrova** [comment]
[Pre-commit](http://intel-ci.intel.com/ee459799-773a-f165-bdc6-a4bf010d0e2e)

**Review by napetrov — APPROVED** [review]
Looks good for me. 

@samir-nasibli  @Alexsandruss  - please review

**Review by Alexsandruss — APPROVED** [review]

**Review by samir-nasibli — APPROVED** [review]
Thank you! Looks good

**Pull request merged**
