### PR TITLE
Fix SVR test with RBF kernel

### PR DESCRIPTION
**Pull request by OnlyDeniko**

### CODE REVIEW

**Comment by OnlyDeniko** [comment]
/intelci: run
set ext_build=f5c160bf62a1a3f568ad78c9fd830499c508cd2c

**Comment by OnlyDeniko** [comment]
/intelci: run
set ext_build=ebd38dc6-2784-f1a2-92a7-8cdcd4b723a1

**Comment by OnlyDeniko** [comment]
/intelci: run
set ext_build=ebd38dc6-2784-f1a2-92a7-8cdcd4b723a1

**Review by owerbat — APPROVED** [review]

**Pull request merged**
