### PR TITLE
deps: Update scipy script from major release

### PR DESCRIPTION
**Pull request by ethanglaser**
# Description
Scipy just had major release (0.12) which is now being installed with our sklearn1.3 validation - need to downgrade for compatibility. Should resolve sporadic `scipy flapack liwork dsyevr` errors in conformance steps.

### CODE REVIEW

**Review by md-shafiul-alam — APPROVED** [review]
Assuming green ci

**Comment by ethanglaser** [comment]
Looks like scipy version compatibility may be more related to numpy version than sklearn version - https://github.com/scipy/scipy/releases

**Comment by icfaust** [comment]
I have made a ticket to investigate the numpy dependency issue, and have left it unassigned. As my analysis of this problem matches Ethan's solution. I will pull in this PR now.

**Pull request merged**
