### PR TITLE
Enable PCA deselected test

### PR DESCRIPTION
**Pull request by md-shafiul-alam**
### Description 
The test was deselected due to a single value mismatch between PCA transform run on full dataset vs in batches on PVC. This  attempts to reenable the test and resolve the issue if it still persists.  

Fixes # - _issue number(s) if exists_

- [x] I have reviewed my changes thoroughly before submitting this pull request.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes, if necessary (updated in # - _add PR number_)
- [x] The unit tests pass successfully.
- [x] I have run it locally and tested the changes extensively.
- [x] I have resolved any merge conflicts that might occur with the base branch.
- [x] Git commit message contains an appropriate signed-off-by string _(see [CONTRIBUTING.md](https://github.com/intel/scikit-learn-intelex/blob/main/CONTRIBUTING.md#pull-requests) for details)_
- [x] I have added a respective label(s) to PR if I have a permission for that.

### CODE REVIEW

**Comment by md-shafiul-alam** [comment]
Currently this re-enabling doesn't cause any failures in private ci or nightly scope. But could potentially resume as the failure was sporadic to start with. In my opinion, we should merge this and continue watching the nightly. Nightly scope: https://intel-ci.intel.com/ef3fc510-c8d9-f110-b022-a4bf010d0e2e. The failures here are not relevant to the changes made on this PR.

**Review by icfaust — APPROVED** [review]
Full green CI. Lovin' it.

Also good catch. Make sure to message the person on monitoring, or add it as a note somewhere.

**Review by samir-nasibli — APPROVED** [review]

**Pull request merged**
