### PR TITLE
Modify checks on alpha, l1_ratio, max_iter in coordinate descent

### PR DESCRIPTION
**Pull request by md-shafiul-alam**
# Description
Added checks on alpha, and max_iter to improve alignment with scikit-learn.
reverted back checks on l1_ratio

Details of changes made in the pull request:
alpha: added a check to raise value error if alpha is < 0.
l1_ratio: proposed changes were failing internal ci due to differences in how scikit-learn and scikit-learn-intelex handles error, so all changes were discarded and reverted back to original code to match with internal ci .
max_iter: added a check to raise value error if max_iter < 1.

### CODE REVIEW

**Comment by samir-nasibli** [comment]
Could you please update the description and provide full information why we are doing changes on these check

**Comment by samir-nasibli** [comment]
> # Description
> modify checks on alpha, l1_ratio, max_iter to improve alignment with scikit-learn

Could you please provide full information: scikit-learn version. Is this alignment ok for the previous scikit-learn versions?

**Comment by md-shafiul-alam** [comment]
> 

More information added. The changes should not have any effect on the functionality of the algorithm in any version of sklearn except filtering out some undesirable input.

**Comment by samir-nasibli** [comment]
Thank you @md-shafiul-alam for the update. So we have to resolve MacOS fail first

**Comment by Alexsandruss** [comment]
Replaced in stock sklearn with parameter constraints and applied in https://github.com/intel/scikit-learn-intelex/pull/1145.

**Pull request closed without merging**
