### PR TITLE
Enable serialization in `daal4py` algorithm classes

### PR DESCRIPTION
**Pull request by david-cortes-intel**
### Description

fixes https://github.com/intel/scikit-learn-intelex/issues/425

This PR adds support for serialization of the algorithm classes in `daal4py`.

Since they do not store data nor results, the logic is simply to store the init parameters that were passed, and call the initializer again with those same parameters.

I wasn't sure where to add a unit test for this so I created a new test file.

---

Checklist to comply with before moving PR from draft:

**PR completeness and readability**

- [x] I have reviewed my changes thoroughly before submitting this pull request.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation to reflect the changes or created a separate PR with update and provided its number in the description, if necessary.
- [x] Git commit message contains an appropriate signed-off-by string _(see [CONTRIBUTING.md](https://github.com/intel/scikit-learn-intelex/blob/main/CONTRIBUTING.md#pull-requests) for details)_.
- [x] I have added a respective label(s) to PR if I have a permission for that.  
- [x] I have resolved any merge conflicts that might occur with the base branch.

**Testing**

- [x] The unit tests pass successfully.
- [x] I have run it locally and tested the changes extensively.

**Performance**

- [ ] I have measured performance for affected algorithms using [scikit-learn_bench](https://github.com/IntelPython/scikit-learn_bench) and provided at least summary table with measured data, if performance change is expected.
- [ ] I have provided justification why performance has changed or why changes are not expected.

### CODE REVIEW

**Comment by samir-nasibli** [comment]
@david-cortes-intel please address fails. Moving to draft for now

**Review by icfaust — APPROVED** [review]
If you could add another algo to the test, I would be happy. Still good to merge as is. Honestly impressive work.

**Comment by david-cortes-intel** [comment]
Added a test with KMeans also.

**Comment by david-cortes-intel** [comment]
The failing CI jobs appear to be happening elsewhere too and are unrelated to the changes here.

**Pull request merged**
