### PR TITLE
KMeans fix 

### PR DESCRIPTION
**Pull request by KulikovNikita**

### CODE REVIEW

**Comment by KulikovNikita** [comment]
Manually started CI: http://intel-ci.intel.com/ee1becc5-c04d-f130-8c9f-a4bf010d0e2e

**Review by ethanglaser — APPROVED** [review]

**Review by ethanglaser — CHANGES_REQUESTED** [review]
Actually it looks like there is additional fix required based on CI job

**Comment by KulikovNikita** [comment]
http://intel-ci.intel.com/ee1c0919-9061-f1b0-a157-a4bf010d0e2e

**Review by ethanglaser — APPROVED** [review]

**Comment by samir-nasibli** [comment]
Sorry, for the late comment, but what exactly was fixed? No description is provided and there is not test case that was deselected for this. @KulikovNikita could you please clarify the fix?

**Pull request merged**
