### PR TITLE
Enabling Nightly cron run

### PR DESCRIPTION
**Pull request by napetrov**
Enabling Nightly cron job

### CODE REVIEW

**Review by homksei — APPROVED** [review]

**Comment by ethanglaser** [comment]
Looks like Nightly jobs are failing, error messages indicate missing packages but install logs don't show any issues...

**Comment by ethanglaser** [comment]
scikit-learn install issue is fixed but still a problem with coverity runs - not sure about this. Nightly runs are now running properly and first look at  sklearn 1.5. Not sure if we want to merge this now with the red CI or resolve all issues first, but at least one source of many failures is deprecation of TSNE `n_iter` for `max_iter` (https://github.com/scikit-learn/scikit-learn/pull/28471/files#diff-dec5f8e0a26a0b2f3a2200eb52b0079fc1ec90b1ad04940bf7fe00d2aad7851b)

**Comment by napetrov** [comment]
I would say - yes, with plan for addressing problems. At least this would enable Coverity and Jupyter validation. 

Coverity fails in pr because key is not passed to job

**Review by ethanglaser — APPROVED** [review]

**Pull request merged**
